name: app_cloner_helper
description: A helper app that lists installed apps and creates 4 launch shortcuts inside the app.
publish_to: "none"

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_apps: ^2.0.2
  package_info_plus: ^3.0.2

flutter:
  uses-material-design: true
